#!/bin/bash

# this script takes a script name, creates it in ~/bin,
# makes it executable, writes its hashbang title and edits it.

function main
{
    if [[ $# -ne 1 ]]; then
        echo "Missing script argument." 1>&2
        echo "Usage: create_script <script>" 1>&2
        exit 1
    fi
    scriptname="$1"
    if script_already_exists; then
        echo "$scriptname is an existing command, pick another." 1>&2
        exit 1
    fi
    bindir="$HOME/bin"
    verify_bindir
    scriptpath="$bindir/$scriptname"
    verify_scriptpath
    write_script_template
    make_script_executable
    open_script_in_editor
    echo "Created new script at $scriptpath"
    exit 0
}

function script_already_exists
{
    if type "$scriptname" &> /dev/null; then
        return 0
    else
        return 1
    fi
}

function verify_bindir
{
    if [[ ! -d $bindir ]]; then
        echo "Creating $bindir"
        if ! mkdir "$bindir"; then
            echo "Failed to create $bindir" 1>&2
            exit 1
        fi
    fi
}

function verify_scriptpath
{
    if [[ -e $scriptpath ]]; then
        read -r -p "Script already exists. Are you sure you want to overwrite it? [y/N] " overwrite
        if [[ ! $overwrite = "Y" && ! $overwrite = "y" ]]; then
            exit 0
        fi
    fi
}

function write_script_template
{
    cat > "$scriptpath" << EOL
#!/bin/bash

# insert script description here.

function main
{
    # write me
    exit 0
}

main "\$@"

EOL
}

function make_script_executable
{
    chmod u+x "$scriptpath"
}

function open_script_in_editor
{
    if [[ $EDITOR ]]; then
        $EDITOR "$scriptpath"
    fi
}

main "$@"

