#!/bin/bash

# this script takes a script name, creates it in ~/bin,
# makes it executable, writes its hashbang title and edits it.

# TODO:  See how I can expand the RE pattern to include a dot, a space and a hyphen.

main()
{
    if [[ $# -ne 1 ]]; then
        echo "Usage: create_script <script>" >&2
        exit 1
    fi
    scriptname="$1"
    if ! is_filename_valid; then
        echo "Invalid file name." >&2
        exit 1
    fi
    if script_already_exists; then
        echo "$scriptname is an existing command, pick another." >&2
        exit 1
    fi
    bindir="$HOME/bin"
    verify_bindir
    scriptpath="$bindir/$scriptname"
    verify_scriptpath
    write_script_template
    make_script_executable
    open_script_in_editor
    echo "Created new script at $scriptpath"
    exit 0
}

is_filename_valid()
{
    valid_filename_pattern='^[[:alpha:]]\w*$'
    if [[ $scriptname =~ $valid_filename_pattern ]]; then
        true
    else
        false
    fi
}

script_already_exists()
{
    if type -- "$scriptname" > /dev/null 2>&1; then
        true
    else
        false
    fi
}

verify_bindir()
{
    if [[ ! -d $bindir ]]; then
        echo "Creating $bindir"
        if ! mkdir "$bindir"; then
            echo "Failed to create $bindir" >&2
            exit 1
        fi
    fi
}

verify_scriptpath()
{
    if [[ -e $scriptpath ]]; then
        read -r -p "Script already exists. Are you sure you want to overwrite it? [y/N] " overwrite
        if [[ $overwrite != [Yy] ]]; then
            exit 0
        fi
    fi
}

write_script_template()
{
    cat > "$scriptpath" << END
#!/bin/bash

# insert script description here.

main()
{
    # write me
    exit 0
}

main "\$@"

END
}

make_script_executable()
{
    chmod u+x -- "$scriptpath"
}

open_script_in_editor()
{
    if [[ $EDITOR ]]; then
        $EDITOR "$scriptpath"
    fi
}

main "$@"

