#!/bin/bash

# edits modified files in a git repository
# great chance to practice awk
# TODO: Improve awk quality

main()
{
    if ! is_vim_installed; then
        echo "Vim is not installed." >&2
        exit 1
    fi
    if ! is_cwd_a_git_repo; then
        echo "Current directory is not a git repository." >&2
        exit 1
    fi
    files_to_edit=$(get_modified_files)
    if [[ $files_to_edit ]]; then
        edit_files $files_to_edit
    else
        echo "There are no modified files to edit." >&2
    fi
    exit 0
}

is_vim_installed()
{
    if type vim &> /dev/null; then
        return 0
    else
        return 1
    fi
}

is_cwd_a_git_repo()
{
    if [[ -d $PWD/.git ]]; then
        return 0
    else
        return 1
    fi
}

get_modified_files()
{
    git_status_output=$(git status)
    awk '/new|modified/{if ($1 == "new") print $3; else if ($1 == "modified:") print $2}' <<< "$git_status_output"
}

edit_files()
{
    vim -p "$@"
}

main

# just for testes
