#!/bin/bash

# Friendly user interface for running game roms emulated by Mednafen
# Adir Tzuberi, December 27, 2018

main()
{
    title
    cd "$HOME/Games/Mednafen"
    print_available_options
    prompt_user_selection "console"
    cd "$selected_option"
    print_available_options
    prompt_user_selection "game"
    play_game "$selected_option"
    exit $?
}

title()
{
    echo
    echo "----------------"
    echo "Old School Games"
    echo "----------------"
    echo
}

print_available_options()
{
    available_options=( "" * )
    unset available_options[0]
    local number_of_options=${#available_options[@]}
    for (( option_number=1; option_number <= number_of_options; ++option_number )); do
        option_display_name="${available_options[option_number]% (*)*.zip}"
        echo "$option_number) $option_display_name"
    done
    echo
    echo "$option_number) Exit"
}

prompt_user_selection()
{
    local option_type="$1"
    local prompt_message="Select a $option_type"
    local number_of_options=${#available_options[@]}
    local exit_option=$(( number_of_options + 1 ))
    local selection_made=false
    while ! $selection_made; do
        echo
        read -r -p "$prompt_message: " user_selection
        if (( user_selection > 0 && user_selection <= number_of_options )) 2> /dev/null; then
            selected_option="${available_options[user_selection]}"
            selection_made=true
        elif (( user_selection == exit_option )) 2> /dev/null; then
            exit 0
        else
            echo "Invalid input, try again."
        fi
    done
    echo
}

play_game()
{
    selected_game="$1"
    mednafen "$selected_game" > /dev/null 2>&1
}

main "$@"

